### ISSUE TITLE
docker file

### ISSUE THREAD

**Issue by elvince** [jihchi/mermaid.ink#96]
Hi,

I'm trying to build your docker file but when I run it I'm facing this:

```
Error: Failed to launch the browser process!

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

[0819/133818.290323:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)

[0819/133818.290400:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)

[0819/133818.292678:ERROR:directory_reader_posix.cc(42)] opendir /tmp/Crashpad/attachments/56fed145-5bfe-432c-8d49-a36dac5c13b0: No such file or directory (2)



TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md


    at onClose (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)

    at ChildProcess.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:280:24)

    at ChildProcess.emit (node:events:539:35)

    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

error Command failed with exit code 1.
```

It seems to be linked to user namespace setup in the OS, but I'm not sure to properly understand.

Thanks for your help

**Comment by jihchi** [comment]
If you run it locally, does it work when you add `--cap-add=SYS_ADMIN` to your `docker run`?

**Comment by elvince** [comment]
yes it is with this parameter.
Isn't it it any other way to run this without giving such priviledge to this container?

**Comment by jihchi** [comment]
I'm not aware of any,  you probably can find answer from puppeteer's [doc](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md).
